# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 01:46
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('roles', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u89d2\u8272')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u8d26\u6237\u8868',
                'verbose_name_plural': '\u8d26\u6237\u8868',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OpsUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('vname', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8be6\u7ec6\u540d\u79f0')),
                ('public_key', models.TextField(verbose_name='\u7528\u6237\u516c\u94a5')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='\u79d8\u94a5\u6307\u7eb9')),
                ('login_user', models.CharField(max_length=32, verbose_name='\u767b\u5f55\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba4\u8bc1\u7528\u6237\u8868',
                'verbose_name_plural': '\u8ba4\u8bc1\u7528\u6237\u8868',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('vname', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8be6\u7ec6\u9879\u76ee\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8868',
                'verbose_name_plural': '\u9879\u76ee\u8868',
            },
        ),
        migrations.AddField(
            model_name='opsuserprofile',
            name='project',
            field=models.ManyToManyField(to='ops.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
