# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=15)),
                ('loginuser', models.CharField(blank=True, max_length=512, null=True)),
                ('realuser', models.CharField(blank=True, max_length=512, null=True)),
                ('fromip', models.CharField(blank=True, max_length=15, null=True)),
                ('logintime', models.DateTimeField()),
                ('logintype', models.IntegerField(blank=True, null=True)),
                ('command', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
