# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_auto_20180626_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lander',
            field=models.CharField(max_length=32, verbose_name='\u4e2d\u63a7\u673a'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'lander')]),
        ),
    ]
