# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_auto_20180627_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsuserprofile',
            name='islimited',
            field=models.PositiveSmallIntegerField(choices=[(0, 'status1'), (1, 'status2'), (2, 'status3')], default=0),
        ),
    ]
