# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20180703_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsuserprofile',
            name='login_user',
            field=models.PositiveSmallIntegerField(choices=[(0, 'root'), (1, 'common')], default=1, verbose_name='\u767b\u5f55\u7528\u6237'),
        ),
    ]
