# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u914d\u7f6e\u7c7b\u578b')),
                ('specific_config', models.TextField(verbose_name='\u914d\u7f6e\u8be6\u60c5')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u4e3b\u673a\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='DBms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_ip', models.CharField(max_length=16, unique=True, verbose_name='\u516c\u7f51ip')),
                ('inner_ip', models.CharField(max_length=16, unique=True, verbose_name='\u5185\u7f51ip')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'down'), (1, 'up'), (2, 'cancel'), (3, 'known')], default=0, verbose_name='\u673a\u5668\u72b6\u6001')),
                ('create_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('host_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excute.Configuration')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u8868',
                'verbose_name_plural': '\u4e3b\u673a\u8868',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8868',
                'verbose_name_plural': '\u9879\u76ee\u8868',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_num', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'DB'), (1, 'Redis'), (2, 'Serverlist'), (4, 'cobar/mycat'), (5, 'GM'), (6, 'Sfs'), (7, 'api'), (8, 'DB_backup'), (9, 'other')], verbose_name='\u670d\u52a1\u7c7b\u578b')),
                ('deploy_time', models.DateTimeField(verbose_name='\u90e8\u7f72\u65f6\u95f4')),
                ('version', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u8f6f\u4ef6\u7248\u672c')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u76d1\u542c\u7aef\u53e3')),
                ('dns_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1\u57df\u540d')),
                ('use_status', models.PositiveSmallIntegerField(choices=[(0, '\u5907\u7528'), (1, '\u4f7f\u7528')], default=1, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('flags', models.CharField(blank=True, max_length=32, null=True)),
                ('install_way', models.PositiveSmallIntegerField(choices=[(0, 'source'), (1, 'yum/rpm'), (2, 'docker'), (3, 'other')], verbose_name='\u5b89\u88c5\u65b9\u5f0f')),
                ('deploy_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excute.Hosts', verbose_name='\u6240\u5c5e\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u90e8\u7f72\u670d\u52a1\u8868',
                'verbose_name_plural': '\u90e8\u7f72\u670d\u52a1\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u8868',
                'verbose_name_plural': '\u6807\u7b7e\u8868',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excute.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='dbms',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excute.Services', verbose_name='\u4e3b\u5e93'),
        ),
        migrations.AddField(
            model_name='dbms',
            name='slave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pk', to='excute.Services', verbose_name='\u4ece\u5e93'),
        ),
    ]
