# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excute', '0004_auto_20180922_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBsfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dbms',
            options={'verbose_name': 'db\u4ece\u4e3b\u8868', 'verbose_name_plural': 'db\u4e3b\u4ece\u8868'},
        ),
        migrations.AddField(
            model_name='dbsfs',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excute.DBms', verbose_name='\u6570\u636e\u5e93'),
        ),
        migrations.AddField(
            model_name='dbsfs',
            name='sfs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='excute.Services', verbose_name='sfs'),
        ),
    ]
