# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-22 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excute', '0005_auto_20180922_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbsfs',
            options={'verbose_name': 'sfsdb\u4e3b\u8868', 'verbose_name_plural': 'sfsdb\u4e3b\u4ece\u8868'},
        ),
    ]
